"""Constants used across multiple microservices in the IDSS Engine"""

# Copied from Decision Support Display's forecastVarConfig.js. This is every weather variable that
# a user can request in a Vulnerability a.k.a. DSS Profile
FORECAST_VAR_CONFIG = {
    "field": {
        "AppTemp": {
            "abvName": "Apt Temp",
            "timeWindowHours": 0,
            "units": ["Fahrenheit", "Celsius"],
        },
        "Ceiling": {"abvName": "Ceiling", "timeWindowHours": 0, "units": ["KiloFeet"]},
        "CloudCover": {"abvName": "Cld Cover", "timeWindowHours": 0, "units": ["Percent"]},
        "DewPoint": {
            "abvName": "Dew Pt",
            "timeWindowHours": 0,
            "units": ["Fahrenheit", "Celsius"],
        },
        "EchoTop": {"abvName": "18dBZ ET", "timeWindowHours": 0, "units": ["KiloFeet"]},
        "HeatIdx": {
            "abvName": "Heat Index",
            "timeWindowHours": 0,
            "units": ["Fahrenheit", "Celsius"],
        },
        "Ice:1HR": {"abvName": "Frz Rain", "timeWindowHours": 1, "units": ["Inches"]},
        "Ice:3HR": {"abvName": "Frz Rain", "timeWindowHours": 3, "units": ["Inches"]},
        "Ice:6HR": {"abvName": "Frz Rain", "timeWindowHours": 6, "units": ["Inches"]},
        "Ice:24HR": {"abvName": "Frz Rain", "timeWindowHours": 24, "units": ["Inches"]},
        "Lightning": {"abvName": "Lightning", "timeWindowHours": 0, "units": ["Lightning"]},
        "MaxTemp": {
            "abvName": "Max Temp",
            "timeWindowHours": 24,
            "units": ["Fahrenheit", "Celsius"],
        },
        "MinTemp": {
            "abvName": "Min Temp",
            "timeWindowHours": 24,
            "units": ["Fahrenheit", "Celsius"],
        },
        "MaxRef": {"abvName": "Comp Refl", "timeWindowHours": 0, "units": ["DBZ"]},
        "MaxRh": {"abvName": "Max RH", "timeWindowHours": 24, "units": ["Percent"]},
        "MinRh": {"abvName": "Min RH", "timeWindowHours": 24, "units": ["Percent"]},
        "ProbPrecip": {"abvName": "Prob Precip", "timeWindowHours": 0, "units": ["Percent"]},
        "ProbThdr:1HR": {"abvName": "Prob Thdr", "timeWindowHours": 1, "units": ["Percent"]},
        "ProbThdr:3HR": {"abvName": "Prob Thdr", "timeWindowHours": 3, "units": ["Percent"]},
        "ProbThdr:6HR": {"abvName": "Prob Thdr", "timeWindowHours": 6, "units": ["Percent"]},
        "ProbThdr:12HR": {"abvName": "Prob Thdr", "timeWindowHours": 12, "units": ["Percent"]},
        "Precip:1HR": {
            "abvName": "Precip",
            "timeWindowHours": 1,
            "units": ["Inches", "Millimeters"],
        },
        "Precip:3HR": {
            "abvName": "Precip",
            "timeWindowHours": 3,
            "units": ["Inches", "Millimeters"],
        },
        "Precip:6HR": {
            "abvName": "Precip",
            "timeWindowHours": 6,
            "units": ["Inches", "Millimeters"],
        },
        "Precip:24HR": {
            "abvName": "Precip",
            "timeWindowHours": 24,
            "units": ["Inches", "Millimeters"],
        },
        "RH": {"abvName": "RH", "timeWindowHours": 0, "units": ["Percent"]},
        "Snow:1HR": {"abvName": "Snow", "timeWindowHours": 1, "units": ["Inches", "Feet"]},
        "Snow:3HR": {"abvName": "Snow", "timeWindowHours": 3, "units": ["Inches", "Feet"]},
        "Snow:6HR": {"abvName": "Snow", "timeWindowHours": 6, "units": ["Inches", "Feet"]},
        "Snow:12HR": {"abvName": "Snow", "timeWindowHours": 12, "units": ["Inches", "Feet"]},
        "Snow:24HR": {"abvName": "Snow", "timeWindowHours": 24, "units": ["Inches", "Feet"]},
        "Snow:48HR": {"abvName": "Snow", "timeWindowHours": 48, "units": ["Inches", "Feet"]},
        "Temp": {"abvName": "Temp", "timeWindowHours": 0, "units": ["Fahrenheit", "Celsius"]},
        "VIL": {"abvName": "VIL", "timeWindowHours": 0, "units": ["KgPerMeter2"]},
        "Visibility": {"abvName": "Vis", "timeWindowHours": 0, "units": ["Miles", "Kilometers"]},
        "WaveHeight": {"abvName": "Wave Hgt", "timeWindowHours": 0, "units": ["Feet", "Meters"]},
        "WBGT": {"abvName": "WBGT", "timeWindowHours": 0, "units": ["Fahrenheit", "Celsius"]},
        "WindChill": {
            "abvName": "Wnd Chl",
            "timeWindowHours": 0,
            "units": ["Fahrenheit", "Celsius"],
        },
        "WindDir": {"abvName": "Wnd Dir", "timeWindowHours": 0, "units": ["Degrees"]},
        "WindGust": {
            "abvName": "Wnd Gst",
            "timeWindowHours": 0,
            "units": ["MilesPerHour", "Knots"],
        },
        "WindSpeed": {
            "abvName": "Wnd Spd",
            "timeWindowHours": 0,
            "units": ["MilesPerHour", "Knots"],
        },
    },
    "units": {
        "ExceedanceIndex": {"abv": "", "name": ""},
        # "None": {"abv": "", "name": ""},
        "Inches": {"abv": '"', "name": "Inches"},
        "Feet": {"abv": "'", "name": "Feet"},
        "Miles": {"abv": "mi", "name": "Miles"},
        "NauticalMiles": {"abv": "nmi", "name": "Nautical Miles"},
        "Meters": {"abv": "m", "name": "Meters"},
        "Millimeters": {"abv": "mm", "name": "Millimeters"},
        "Centimeters": {"abv": "cm", "name": "Centimeters"},
        "Kilometers": {"abv": "km", "name": "Kilometers"},
        "MetersPerSecond": {"abv": "m/s", "name": "Meters Per Second"},
        "InchesPerSecond": {"abv": "in/s", "name": "Inches Per Second"},
        "MilesPerHour": {"abv": "mph", "name": "Miles Per Hour"},
        "Knots": {"abv": "kt", "name": "Knots"},
        "Fahrenheit": {"abv": "°F", "name": "Fahrenheit"},
        "Kelvin": {"abv": "K", "name": "Kelvin"},
        "Celsius": {"abv": "°C", "name": "Celsius"},
        "KgPerMeter2": {"abv": "kg/m^2", "name": "Kg Per Meter Squared"},
        "MmPerSec": {"abv": "mm/s", "name": "Millimeters Per Second"},
        "Hours": {"abv": "hr", "name": "Hours"},
        "Radians": {"abv": "rad", "name": "Radians"},
        "Degrees": {"abv": "°", "name": "Degrees"},
        "Percent": {"abv": "%", "name": "Percent"},
        "Kilofeet": {"abv": "kft", "name": "Kilofeet"},
        "DBZ": {"abv": "dBZ", "name": "dBZ"},
        "Lightning": {"abv": "LAL", "name": "Lightning Activity Level"},
    },
    "relational": {
        "GREATER THAN OR EQUAL": {"text": "greater than or equal to", "symbol": ">="},
        "LESS THAN OR EQUAL": {"text": "less than or equal to", "symbol": "<="},
        "GREATER THAN": {"text": "greater than", "symbol": ">"},
        "LESS THAN": {"text": "less than", "symbol": "<"},
    },
    "criteriaBuilderFields": {
        "aviation": ["Ceiling", "CloudCover", "Visibility"],
        "precipitation": [
            "Precip:1HR",
            "Precip:6HR",
            "Precip:24HR",
            "Ice:1HR",
            "Ice:6HR",
            "Ice:24HR",
            "Snow:1HR",
            "Snow:6HR",
            "Snow:24HR",
            "Snow:48HR",
            "ProbThdr:1HR",
            "ProbThdr:3HR",
            "ProbThdr:6HR",
            "ProbThdr:12HR",
        ],
        "surface": ["AppTemp", "Temp", "WBGT", "DewPoint", "RH", "WindGust", "WindSpeed"],
    },
}
